branches:
    - released

verifyConditions:
    - "@semantic-release/git"
    - "@semantic-release/github"

generateNotes:
  - "@semantic-release/release-notes-generator"

prepare:
    - path: "@semantic-release/changelog"
      changelogFile: "CHANGELOG.md"
      changelogTitle: "Changelog"
    - path: "@semantic-release/git"
      assets: ["CHANGELOG.md"]

publish:
    - path: "@semantic-release/npm"
      npmPublish: true
      tarballDir: dist
    - path: "@semantic-release/github"
      assets: dist/*.tgz

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"